@First_REST_API_HostAddress = http://localhost:5009

GET {{First_REST_API_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{First_REST_API_HostAddress}}/api/books
Accept: application/json

###
GET {{First_REST_API_HostAddress}}/api/books/2
Accept: application/json
